### ISSUE TITLE
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'form'. Did you forget to register or load this tag?

### ISSUE THREAD

**Issue by maffsojah** [viewflow/django-material#270]
Hello,
I tried to create LoginForm and RegisterForm in my application using the example in the demo app. I am getting the error `django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'form'. Did you forget to register or load this tag?`  I have checked and I think the error is coming from this block with the `form` tag as shown below:
`template = Template("""

    {% form %}
        {% part form.email prefix %}<i class="material-icons prefix">email</i>{% endpart %}
        {% part form.password prefix %}<i class="material-icons prefix">lock</i>{% endpart %}
        {% attr form.keep_logged 'group' class append %}right-align{% endattr %}
    {% endform %}
    """)`

I am using Django 1.10.6 with Python 2.7 and the error trace is 

```
Unhandled exception in thread started by <function wrapper at 0x7ff815daf320>
Traceback (most recent call last):
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/maffsojah/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/tbank/tbank/urls.py", line 26, in <module>
    from . import forms, widget_forms, admin_forms
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/tbank/tbank/forms.py", line 137, in <module>
    class LoginForm(forms.Form):
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/tbank/tbank/forms.py", line 149, in LoginForm
    """)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/maffsojah/Projects/HIT_400/capstone_project/web/lib/python2.7/site-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'form'. Did you forget to register or load this tag?
```

**Comment by kmmbvnr** [comment]
you need `{% load material_form %}`

http://docs.viewflow.io/material_forms.html

**Comment by maffsojah** [comment]
sorry, that did not solve the issue @kmmbvnr .  I loaded the material_form template tag library in my base template but still getting the same error. Just for trial, I added in my form and got `SyntaxError: invalid syntax`

**Comment by kmmbvnr** [comment]
Please, spend more time on reading existing documentation, before asking.

https://docs.djangoproject.com/en/1.11/ref/templates/language/

![the django template language django documentation django](https://cloud.githubusercontent.com/assets/282529/25322994/b2ed39f0-28dd-11e7-93f2-9c16394688f8.png)

**Comment by SalMax** [comment]
Hello, sorry for re-open the issue

I'm trying to make a material form through Material Frontend and ModelForm. 

I'm getting the same error and I have `{% load material_form %}` in my template (I'm overriding the form.html frontend template via `templates\<myapp>\<my_namespace>_edit.html`

I can't find any example in docs about this (using frontend, ModelView and ModelViewSet)

My apologies if I'm loosing something basic.

Thanks.

**Comment by SalMax** [comment]
I have found my error... 

In orde to use form tag, we have to include this in settings.py:
```
 'builtins': [
                'material.templatetags.material_form',
            ],
```
@kmmbvnr please consider include this config in [http://docs.viewflow.io/material_forms.html](material form docs)

Thanks
