### ISSUE TITLE
Inherited fields not visible in admin forms

### ISSUE THREAD

**Issue by xscheiner** [viewflow/django-material#29]
I have the following in forms.py

```
class ContactForm(autocomplete_light.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
```

and in admin.py

```
class ContactAdmin(ModelAdminWithReadOnly):
    list_display = (
        'first_name', 'last_name', 'title', 'email', 'account',
        'attendee_count',
    )
    search_fields = (
        'id', 'first_name', 'last_name', 'email', 'account__name', 'title',
        'department',
    )

    readonly_fields = ('id', 'modified',)
    fields = (
        'id', 'account', 'first_name', 'last_name', 'title', 'department',
        'email', 'phone', 'mobile_phone', 'twitter', 'picture_url',
        'linked_in', 'how_heard', 'notes', 'modified'
    )

    inlines = (BookingInline, AttendeeInline,)

    form = ContactForm
```

When I try to run, I get:

```
ERROR [django.request:256] Internal Server Error: /admin/apricot/contact/12706/
Traceback (most recent call last):
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/templatetags/material_form.py", line 101, in render
    return template.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/templatetags/material_form.py", line 152, in render
    value = self.nodelist.render(context).strip()
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/templatetags/material_form.py", line 152, in render
    value = self.nodelist.render(context).strip()
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/templatetags/material_form_internal.py", line 64, in render
    return element.render(context, **options)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/base.py", line 34, in render
    return template.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/templatetags/material_form_internal.py", line 64, in render
    return element.render(context, **options)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/base.py", line 34, in render
    return template.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/templatetags/material_form_internal.py", line 64, in render
    return element.render(context, **options)
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/material/base.py", line 144, in render
    bound_field = form[self.field_name]
  File "/srv/sites/myportal/env/lib/python2.7/site-packages/django/forms/forms.py", line 167, in __getitem__
    "Key %r not found in '%s'" % (name, self.__class__.__name__))
KeyError: u"Key 'id' not found in 'ContactForm'"
```

If I remove the id and modified fields from ContactAdmin, the problem goes away. The model inherits those from the base classes it extends. So the problem appears to be only with inherited fields on the model.

**Comment by kmmbvnr** [comment]
This is not related to inherited fields. Jusr read_only fields was not supported a long ago.
