### ISSUE TITLE
Material theme color not working on production

### ISSUE THREAD

**Issue by jackquin** [viewflow/django-material#372]
```
INSTALLED_APPS = [
    'material.theme.amber',
    'material',
    'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'django_filters',
.....
```
and there is configuration for  production
```
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'

```
so when i use the `python manage.py collectstatic` command some errors occured.

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 145, in collect
    raise processed
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 303, in _post_process
    content = pattern.sub(converter, content)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 204, in converter
    force=True, hashed_files=hashed_files,
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 352, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 101, in hashed_name
    raise ValueError("The file '%s' could not be found with %r." % (filename, self))
ValueError: The file 'css/mcustomscrollbar/mCSB_buttons.png' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7fd9d45594a8>.

```
can you guys help me.

**Comment by kmmbvnr** [comment]
raise ValueError("The file '%s' could not be found with %r." % (filename, self))
ValueError: The file 'css/mcustomscrollbar/mCSB_buttons.png' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7fd9d45594a8>.


Seems not related to the django-material

**Comment by shintojoseph1234** [comment]
> STATICFILES_DIRS = [
>     os.path.join(BASE_DIR, 'static')
> ]

Comment this code and it will work
