### ISSUE TITLE
frontend and model inheritance

### ISSUE THREAD

**Issue by jpic** [viewflow/django-material#382]
Is model inheritance support by frontend ?

The context processor is unable to find the current_module in the two cases where the models inherit from another in another app, might be a misconfiguration from me and just a  coincidence though. The result is that the views crashes because current_module doesn't find the base template to extend: 

`django.template.exceptions.TemplateSyntaxError: Invalid template name in 'extends' tag: ''. Got this from the 'current_module.base_template' variable.`

```
[18/Dec/2017 12:16:47] "GET /pmt/pmt/ HTTP/1.1" 500 122404
> /home/jpic/src/django-material/material/frontend/context_processors.py(13)modules()
     12     import ipdb; ipdb.set_trace()
---> 13     if request.resolver_match:
     14         module = getattr(request.resolver_match.url_name, 'module', None)

ipdb> request.resolver_match
ResolverMatch(func=material.frontend.views.list.ListModelView, args=(), kwargs={}, url_name=pmt_list, app_names=[], namespaces=[])
ipdb> request.resolver_match.url_name
'pmt_list'
ipdb> request.resolver_match.url_name.module
*** AttributeError: 'str' object has no attribute 'module'
ipdb>                                                                                                                                  

Internal Server Error: /pmt/pmt/
Traceback (most recent call last):
  File "/home/jpic/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/jpic/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/jpic/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/jpic/.local/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/jpic/.local/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/jpic/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/jpic/.local/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/jpic/.local/lib/python3.6/site-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template
    context = processor(self.request)
  File "/home/jpic/src/django-material/material/frontend/context_processors.py", line 13, in modules
    if request.resolver_match:
  File "/home/jpic/src/django-material/material/frontend/context_processors.py", line 13, in modules
    if request.resolver_match:
  File "/usr/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.6/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
[18/Dec/2017 12:17:25] "GET /pmt/pmt/ HTTP/1.1" 500 120603
^C
18/12 2017 13:17:26 jpic@jpic ~/work/betagouv/mrs  (webpack)
$ cat src/pmt/urls.py 
from django.views import generic
from django.urls import include, path, reverse_lazy

from .views import PMTViewSet

urlpatterns = [
    path(
        '',
        generic.RedirectView.as_view(url=reverse_lazy('pmt:pmt_list')),
        name='index'
    ),
    path(
        'pmt/',
        include(PMTViewSet().urls),
    ),
]

18/12 2017 13:17:33 jpic@jpic ~/work/betagouv/mrs  (webpack)
$ cat src/pmt/models.py 
from django.db import models
from django.urls import reverse

from mrsattachment.models import MRSAttachment, MRSAttachmentField
from mrsrequest.models import MRSRequest


class PMTManager(models.Manager):
    def allowed_objects(self, request):
        '''Return PMT QuerySet allowed for this request.'''
        mrsrequests = MRSRequest.objects.allowed_objects(request)
        return self.model.objects.filter(mrsrequest__in=mrsrequests)

    def record_upload(self, mrsrequest, upload):
        '''Create a PMT object from the upload.'''
        return PMT.objects.update_or_create(
            mrsrequest=mrsrequest,
            defaults=dict(
                filename=str(upload),
                binary=MRSAttachment.get_upload_body(upload),
            )
        )[0]


class PMT(MRSAttachment):
    mrsrequest = models.ForeignKey(
        'mrsrequest.MRSRequest',
        on_delete=models.CASCADE,
    )
    binary = MRSAttachmentField(
        'pmt_upload',
        'pmt_download',
        'pmt_destroy',
        verbose_name='Prescription Médicale de Transport'
    )

    objects = PMTManager()

    def get_delete_url(self):
        return reverse('pmt_delete', args=[self.pk])

    class Meta:
        ordering = ['mrsrequest', 'id']

18/12 2017 13:17:35 jpic@jpic ~/work/betagouv/mrs  (webpack)
$ cat src/pmt/views.py 
from material.frontend.views import ModelViewSet

from .models import PMT


class PMTViewSet(ModelViewSet):
    model = PMT
```

You can find the full code here: https://github.com/sgmap/mrs/tree/tbinetruy/src/pmt

**Comment by jpic** [comment]
This was because I was still including urls manually
