### ISSUE TITLE
ModuleNotFoundError: No module named 'material.admin.default'

### ISSUE THREAD

**Issue by Singh-Sg** [viewflow/django-material#480]
My installed app:

INSTALLED_APPS = [
    'reversion',
    'material.admin',
    'material.admin.default',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

ERROR==> 

Traceback (most recent call last):
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'material.admin' has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/Users/developer/projects/Zigway/Backend/envDjango2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'material.admin.default'

Django==2.0
django-material ==1.6.3

Previously it was working fine when i was using django==1.11 and django-material==1.0.0 but i updated my Django version and django-material too.

but not it's not working after the update version.
Could you please provide me some ideas to fix this.

Thank you so much for your help

**Comment by kmmbvnr** [comment]
Admin styles was dropped a while ago #373

**Comment by Singh-Sg** [comment]
I'm using the latest version.
so why I'm getting this error. 

When I created a new project with settings 'material.admin', 'material.admin.default', its working fine.

Could you please suggest me how can I fix and add admin design

**Comment by kmmbvnr** [comment]
material admin styles was removed from this project.
