### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tags'

### ISSUE THREAD

**Issue by mikeumus** [viewflow/django-material#51]
Followed the [install instructions](http://forms.viewflow.io/#installation) but am getting this error stack trace: 

``` 
mikeumus:~/workspace (master) $ sudo python ./manage.py runserver $IP:$PORT
/home/ubuntu/workspace/website/models.py:20: RemovedInDjango19Warning: Model class website.models.Service doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Service(models.Model):

/home/ubuntu/workspace/website/models.py:36: RemovedInDjango19Warning: Model class website.models.Issue doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Issue(models.Model):

/home/ubuntu/workspace/website/models.py:128: RemovedInDjango19Warning: Model class website.models.Bounty doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Bounty(models.Model):

/home/ubuntu/workspace/website/models.py:157: RemovedInDjango19Warning: Model class website.models.UserProfile doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class UserProfile(models.Model):

/home/ubuntu/workspace/website/models.py:20: RemovedInDjango19Warning: Model class website.models.Service doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Service(models.Model):

/home/ubuntu/workspace/website/models.py:36: RemovedInDjango19Warning: Model class website.models.Issue doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Issue(models.Model):

/home/ubuntu/workspace/website/models.py:128: RemovedInDjango19Warning: Model class website.models.Bounty doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Bounty(models.Model):

/home/ubuntu/workspace/website/models.py:157: RemovedInDjango19Warning: Model class website.models.UserProfile doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class UserProfile(models.Model):

Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.

System check identified 1 issue (0 silenced).
November 22, 2015 - 22:04:27
Django version 1.8.6, using settings 'coderbounty.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [Django] ERROR (EXTERNAL IP): Internal Server Error: /
From: root@localhost
To: e, e
Date: Sun, 22 Nov 2015 22:04:33 -0000
Message-ID: <20151122220433.7622.38697@mikeumus-coderbounty-dev-2184777>

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workspace/website/views.py", line 44, in home
    response = render_to_response(template, context, context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 103, in render_to_string
    for engine in _engine_list(using):
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 23, in __init__
    super(DjangoTemplates, self).__init__(params)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/base.py", line 29, in __init__
    "Unknown parameters: {}".format(", ".join(params)))
ImproperlyConfigured: Unknown parameters: TEMPLATE_DEBUG

Request repr(): 
<WSGIRequest
path:/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': '0VKW9LVHlFhwGHscFFn61083bcy6B3O2'},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 u'CSRF_COOKIE': u'0VKW9LVHlFhwGHscFFn61083bcy6B3O2',
 'DJANGO_SETTINGS_MODULE': 'coderbounty.settings',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HOME': '/home/ubuntu',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,es;q=0.6',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'csrftoken=0VKW9LVHlFhwGHscFFn61083bcy6B3O2',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'coderbounty-dev-mikeumus.c9users.io',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '69.125.200.187',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_REGION': 'usw',
 'LANG': 'C',
 'LANGUAGE': 'C.UTF-8',
 'LC_ALL': 'C.UTF-8',
 'LOGNAME': 'root',
 'MAIL': '/var/mail/root',
 'PATH': '/home/ubuntu/.nvm/versions/node/v4.2.1/bin:/usr/local/rvm/gems/ruby-2.2.1/bin:/usr/local/rvm/gems/ruby-2.2.1@global/bin:/usr/local/rvm/rubies/ruby-2.2.1/bin:/mnt/shared/bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/shared/sbin:/opt/gitl:/opt/go/bin:/mnt/shared/c9/app.nw/bin:/usr/local/rvm/bin',
 'PATH_INFO': u'/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '10.240.0.28',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'RUN_MAIN': 'true',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'mikeumus-coderbounty-dev-2184777',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.6',
 'SHELL': '/bin/bash',
 'SUDO_COMMAND': '/usr/bin/python ./manage.py runserver 0.0.0.0:8080',
 'SUDO_GID': '1000',
 'SUDO_UID': '1000',
 'SUDO_USER': 'ubuntu',
 'TERM': 'screen',
 'TZ': 'UTC',
 'USER': 'root',
 'USERNAME': 'root',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fa6922c41e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fa68e359b48>,
 'wsgi.input': <socket._fileobject object at 0x7fa68e303ed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
-------------------------------------------------------------------------------
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workspace/website/views.py", line 44, in home
    response = render_to_response(template, context, context_instance=RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 103, in render_to_string
    for engine in _engine_list(using):
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python2.7/dist-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 23, in __init__
    super(DjangoTemplates, self).__init__(params)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/base.py", line 29, in __init__
    "Unknown parameters: {}".format(", ".join(params)))
ImproperlyConfigured: Unknown parameters: TEMPLATE_DEBUG
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/whitenoise/base.py", line 62, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 97, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 382, in get_traceback_html
    t = DEBUG_ENGINE.from_string(TECHNICAL_500_TEMPLATE)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 153, in from_string
    return Template(template_code, engine=self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 260, in compile_string
    parser = parser_class(tokens)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 35, in __init__
    super(DebugParser, self).__init__(lexer)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 303, in __init__
    self.add_library(lib)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 417, in add_library
    self.tags.update(lib.tags)
AttributeError: 'NoneType' object has no attribute 'tags'
[22/Nov/2015 22:04:33] "GET / HTTP/1.1" 500 59
```

:|

**Comment by kmmbvnr** [comment]
So, how your settings.py looks like?

The error message is related to django-material completely.

**Comment by mikeumus** [comment]
I followed the `TEMPLATES` django 1.8 migration docs you sent me but am still getting the error. Here's the `settings.py` in question:
https://github.com/mikeumus/coderbounty-mikeDev/blob/mikeDev/coderbounty/settings.py#L1

**Comment by kmmbvnr** [comment]
Thanks for reporting! There was `material.frontend.templatetags` lib missing in pypi distributed version.

Fix released. Please use django-material==0.5.1

**Comment by mikeumus** [comment]
Your welcome, thanks for patching! :+1: :)

**Comment by auvipy** [comment]
owh thanks

**Comment by auvipy** [comment]
well It would be nice to have a package version sticker on github repo
