### ISSUE TITLE
Can't get started with Material Frontend

### ISSUE THREAD

**Issue by djjudas21** [viewflow/django-material#513]
Hi there. I've got a Django project which has a crap UI, so I decided to trial Material Frontend instead.

I followed [your docs](http://docs.viewflow.io/material_frontend.html) to get started with a basic installation, and you can see my [minimal diff here](https://github.com/camerahub/camerahub/compare/811_material). But the key parts are my project's `urls.py` and Material's `urls.py`. I've placed my new Material frontend UI at `/ui` instead of `/` so I can hack on it without disrupting my existing UI.

```py
# top level urls
from django.contrib import admin
from django.urls import include, path
from material.frontend import urls as frontend_urls

urlpatterns = [
    path('', include('schema.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('django_prometheus.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('health/', include('health_check.urls')),
    path('docs/', include('sphinxdoc.urls')),
    path('ui/', include('ui.urls')),
    path('ui/', include(frontend_urls)),
]
```

```py
# Material ui urls
from django.conf.urls import url, include
from django.views import generic
from . import views

urlpatterns = [
    url('^$', generic.TemplateView.as_view(template_name="ui/index.html"), name="index"),
    url('^cameramodel/', include(views.CameraModelViewSet().urls)),
    url('^camera/', include(views.CameraViewSet().urls)),
]
```

* Browsing to `/` seems to work, and displays my old UI
* Browsing to `/ui` seems to work, and displays a basic Material UI with a single menu item
* Browsing to `/ui/cameramodel/` breaks with `Reverse for 'cameramodel_add' not found. 'cameramodel_add' is not a valid view function or pattern name.`

I guess `cameramodel_add` is an autogenerated URL from the viewset? I can't figure out where it's coming from or why it is not being included. Is this because I am trying to run my Material UI at a location other than `/`?

I'm a relative beginner at Django so any help you can offer will be greatly appreciated, thanks.

**Comment by kmmbvnr** [comment]
```diff
-    path('ui/', include('ui.urls')),
     path('ui/', include(frontend_urls)),
```

the first line seems redundant. Frontend perform modules app configs auto-discovery

**Comment by djjudas21** [comment]
Thanks for your response. I'm still stuck on this issue. I've tried various combinations of configs but at the moment my global `urls.py` is

```py
urlpatterns = [
    path('', include('ui.urls')),
#    path('', include('schema.urls')),
    path('', include(frontend_urls)),
    ]
```

and the UI module `urls.py` is

```py
urlpatterns = [
    path('', generic.RedirectView.as_view(url='./cameramodel/', permanent=False), name="index"),
    path('cameramodel/', include(views.CameraModelViewSet().urls)),
]
```

If I hit `/ui/cameramodel/` I get

>NoReverseMatch at /ui/cameramodel/
>Reverse for 'cameramodel_add' not found. 'cameramodel_add' is not a valid view function or pattern name.

I still don't understand why `cameramodel_add` can't be found. My `views.py` is

```py
from material.frontend.views import ModelViewSet
from schema import models

class CameraModelViewSet(ModelViewSet):
    model = models.CameraModel
```

Thanks

**Comment by djjudas21** [comment]
I abandoned work on my project because of this blocker, but I've returned to it and I've started trying to reimplement a UI with django-material again from scratch. I'm running into the same error again :disappointed: 

* the parent app is `camerahub`
* the app which contains an existing `models.py` is `schema`
* the app which contains a skeleton Material project is `ui`

The `schema` app used to contain a bunch of views I wrote myself, but I have now deleted everything apart from `models.py`.


```py
# camerahub/urls.py

from django.contrib import admin
from django.urls import include, path
from material.frontend import urls as frontend_urls

urlpatterns = [
    path('', include(frontend_urls)),
    path('', include('schema.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('django_prometheus.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('health/', include('health_check.urls')),
]
```

```py
# ui/urls.py

from unicodedata import name
from django.urls import path, include
from django.views import generic

from . import views


urlpatterns = [
    path('', generic.RedirectView.as_view(url='./cameramodel/'), name="index"),
    path('cameramodel/', include(views.CameraModelViewSet().urls)),
]
```

```py
# ui/views.py

from material.frontend.views import ModelViewSet

from schema import models

# class MyModelViewSet(ModelViewSet):
#    model = models.MyModel

class CameraModelViewSet(ModelViewSet):
    model = models.CameraModel
```

Trying to browse to `http://127.0.0.1:8000/ui/cameramodel/` I get

```
Internal Server Error: /ui/cameramodel/
Traceback (most recent call last):
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/material/frontend/views/list.py", line 531, in dispatch
    return super(ListModelView, self).dispatch(request, *args, **kwargs)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/material/frontend/views/list.py", line 357, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/material/frontend/views/list.py", line 315, in get
    context = self.get_context_data()
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/material/frontend/views/list.py", line 521, in get_context_data
    kwargs['add_url'] = reverse('{}:{}_add'.format(opts.app_label, opts.model_name))
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/jonathan/.cache/pypoetry/virtualenvs/camerahub-FNy4MBnC-py3.10/lib/python3.10/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'cameramodel_add' not found. 'cameramodel_add' is not a valid view function or pattern name.
"GET /ui/cameramodel/ HTTP/1.1" 500 117163
```
