### ISSUE TITLE
Upgraded to .5 version and when runserver starts the following error comes

### ISSUE THREAD

**Issue by auvipy** [viewflow/django-material#55]
self.add_library(lib)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 417, in add_library
    self.tags.update(lib.tags)
AttributeError: 'NoneType' object has no attribute 'tags'

**Comment by auvipy** [comment]
A server error occurred.  Please contact the administrator.

**Comment by auvipy** [comment]
[25/Nov/2015 05:36:06] "GET /admin/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 97, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 382, in get_traceback_html
    t = DEBUG_ENGINE.from_string(TECHNICAL_500_TEMPLATE)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 153, in from_string
    return Template(template_code, engine=self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 260, in compile_string
    parser = parser_class(tokens)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 35, in __init__
    super(DebugParser, self).__init__(lexer)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 303, in __init__
    self.add_library(lib)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 417, in add_library
    self.tags.update(lib.tags)
AttributeError: 'NoneType' object has no attribute 'tags'
[25/Nov/2015 05:36:06] "GET /admin/login/?next=/admin/ HTTP/1.1" 500 59

**Comment by kmmbvnr** [comment]
fix released in 0.5.1

duplicate #51
